name: Run Tests and Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit pytest celery pydantic email-validator redis fastapi httpx

      - name: Install pre-commit hooks
        run: pre-commit install

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Run pytest
        run: |
          pytest app/tests --maxfail=0 --disable-warnings -q
